name: CI
on:
  push:
    branches:
    - master
    
jobs:
  build:
  runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push <YOURLIBRARY>.podspec
